// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: BannerRotationService.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Banners_ShowBanner_FullMethodName           = "/Banners/ShowBanner"
	Banners_ClickBanner_FullMethodName          = "/Banners/ClickBanner"
	Banners_AddBannerToSlot_FullMethodName      = "/Banners/AddBannerToSlot"
	Banners_RemoveBannerFromSlot_FullMethodName = "/Banners/RemoveBannerFromSlot"
)

// BannersClient is the client API for Banners service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannersClient interface {
	ShowBanner(ctx context.Context, in *SelectBannerRequest, opts ...grpc.CallOption) (*SelectBannerResponse, error)
	ClickBanner(ctx context.Context, in *ClickBannerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddBannerToSlot(ctx context.Context, in *AddBannerToSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveBannerFromSlot(ctx context.Context, in *RemoveBannerFromSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type bannersClient struct {
	cc grpc.ClientConnInterface
}

func NewBannersClient(cc grpc.ClientConnInterface) BannersClient {
	return &bannersClient{cc}
}

func (c *bannersClient) ShowBanner(ctx context.Context, in *SelectBannerRequest, opts ...grpc.CallOption) (*SelectBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectBannerResponse)
	err := c.cc.Invoke(ctx, Banners_ShowBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) ClickBanner(ctx context.Context, in *ClickBannerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_ClickBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) AddBannerToSlot(ctx context.Context, in *AddBannerToSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_AddBannerToSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) RemoveBannerFromSlot(ctx context.Context, in *RemoveBannerFromSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_RemoveBannerFromSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannersServer is the server API for Banners service.
// All implementations must embed UnimplementedBannersServer
// for forward compatibility.
type BannersServer interface {
	ShowBanner(context.Context, *SelectBannerRequest) (*SelectBannerResponse, error)
	ClickBanner(context.Context, *ClickBannerRequest) (*empty.Empty, error)
	AddBannerToSlot(context.Context, *AddBannerToSlotRequest) (*empty.Empty, error)
	RemoveBannerFromSlot(context.Context, *RemoveBannerFromSlotRequest) (*empty.Empty, error)
	mustEmbedUnimplementedBannersServer()
}

// UnimplementedBannersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBannersServer struct{}

func (UnimplementedBannersServer) ShowBanner(context.Context, *SelectBannerRequest) (*SelectBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowBanner not implemented")
}
func (UnimplementedBannersServer) ClickBanner(context.Context, *ClickBannerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickBanner not implemented")
}
func (UnimplementedBannersServer) AddBannerToSlot(context.Context, *AddBannerToSlotRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBannerToSlot not implemented")
}
func (UnimplementedBannersServer) RemoveBannerFromSlot(context.Context, *RemoveBannerFromSlotRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBannerFromSlot not implemented")
}
func (UnimplementedBannersServer) mustEmbedUnimplementedBannersServer() {}
func (UnimplementedBannersServer) testEmbeddedByValue()                 {}

// UnsafeBannersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannersServer will
// result in compilation errors.
type UnsafeBannersServer interface {
	mustEmbedUnimplementedBannersServer()
}

func RegisterBannersServer(s grpc.ServiceRegistrar, srv BannersServer) {
	// If the following call pancis, it indicates UnimplementedBannersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Banners_ServiceDesc, srv)
}

func _Banners_ShowBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).ShowBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_ShowBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).ShowBanner(ctx, req.(*SelectBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_ClickBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).ClickBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_ClickBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).ClickBanner(ctx, req.(*ClickBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_AddBannerToSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBannerToSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).AddBannerToSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_AddBannerToSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).AddBannerToSlot(ctx, req.(*AddBannerToSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_RemoveBannerFromSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBannerFromSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).RemoveBannerFromSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_RemoveBannerFromSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).RemoveBannerFromSlot(ctx, req.(*RemoveBannerFromSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Banners_ServiceDesc is the grpc.ServiceDesc for Banners service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Banners_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Banners",
	HandlerType: (*BannersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowBanner",
			Handler:    _Banners_ShowBanner_Handler,
		},
		{
			MethodName: "ClickBanner",
			Handler:    _Banners_ClickBanner_Handler,
		},
		{
			MethodName: "AddBannerToSlot",
			Handler:    _Banners_AddBannerToSlot_Handler,
		},
		{
			MethodName: "RemoveBannerFromSlot",
			Handler:    _Banners_RemoveBannerFromSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BannerRotationService.proto",
}
