// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: BannerRotationService.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID string `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	SlotID  string `protobuf:"bytes,2,opt,name=slotID,proto3" json:"slotID,omitempty"`
}

func (x *SelectBannerRequest) Reset() {
	*x = SelectBannerRequest{}
	mi := &file_BannerRotationService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBannerRequest) ProtoMessage() {}

func (x *SelectBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BannerRotationService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBannerRequest.ProtoReflect.Descriptor instead.
func (*SelectBannerRequest) Descriptor() ([]byte, []int) {
	return file_BannerRotationService_proto_rawDescGZIP(), []int{0}
}

func (x *SelectBannerRequest) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *SelectBannerRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

type SelectBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID string `protobuf:"bytes,1,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *SelectBannerResponse) Reset() {
	*x = SelectBannerResponse{}
	mi := &file_BannerRotationService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectBannerResponse) ProtoMessage() {}

func (x *SelectBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_BannerRotationService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectBannerResponse.ProtoReflect.Descriptor instead.
func (*SelectBannerResponse) Descriptor() ([]byte, []int) {
	return file_BannerRotationService_proto_rawDescGZIP(), []int{1}
}

func (x *SelectBannerResponse) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

type ClickBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID  string `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	SlotID   string `protobuf:"bytes,2,opt,name=slotID,proto3" json:"slotID,omitempty"`
	BannerID string `protobuf:"bytes,3,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *ClickBannerRequest) Reset() {
	*x = ClickBannerRequest{}
	mi := &file_BannerRotationService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickBannerRequest) ProtoMessage() {}

func (x *ClickBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BannerRotationService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickBannerRequest.ProtoReflect.Descriptor instead.
func (*ClickBannerRequest) Descriptor() ([]byte, []int) {
	return file_BannerRotationService_proto_rawDescGZIP(), []int{2}
}

func (x *ClickBannerRequest) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *ClickBannerRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

func (x *ClickBannerRequest) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

type AddBannerToSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   string `protobuf:"bytes,1,opt,name=slotID,proto3" json:"slotID,omitempty"`
	BannerID string `protobuf:"bytes,2,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *AddBannerToSlotRequest) Reset() {
	*x = AddBannerToSlotRequest{}
	mi := &file_BannerRotationService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBannerToSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBannerToSlotRequest) ProtoMessage() {}

func (x *AddBannerToSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BannerRotationService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBannerToSlotRequest.ProtoReflect.Descriptor instead.
func (*AddBannerToSlotRequest) Descriptor() ([]byte, []int) {
	return file_BannerRotationService_proto_rawDescGZIP(), []int{3}
}

func (x *AddBannerToSlotRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

func (x *AddBannerToSlotRequest) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

type RemoveBannerFromSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   string `protobuf:"bytes,1,opt,name=slotID,proto3" json:"slotID,omitempty"`
	BannerID string `protobuf:"bytes,2,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *RemoveBannerFromSlotRequest) Reset() {
	*x = RemoveBannerFromSlotRequest{}
	mi := &file_BannerRotationService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBannerFromSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBannerFromSlotRequest) ProtoMessage() {}

func (x *RemoveBannerFromSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BannerRotationService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBannerFromSlotRequest.ProtoReflect.Descriptor instead.
func (*RemoveBannerFromSlotRequest) Descriptor() ([]byte, []int) {
	return file_BannerRotationService_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveBannerFromSlotRequest) GetSlotID() string {
	if x != nil {
		return x.SlotID
	}
	return ""
}

func (x *RemoveBannerFromSlotRequest) GetBannerID() string {
	if x != nil {
		return x.BannerID
	}
	return ""
}

var File_BannerRotationService_proto protoreflect.FileDescriptor

var file_BannerRotationService_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x13, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f,
	0x74, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x14, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x62, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x63, 0x6b,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x4c, 0x0a, 0x16, 0x41,
	0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x51, 0x0a, 0x1b, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x32, 0x9a, 0x02, 0x0a,
	0x07, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x17, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x14, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x12, 0x1c, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_BannerRotationService_proto_rawDescOnce sync.Once
	file_BannerRotationService_proto_rawDescData = file_BannerRotationService_proto_rawDesc
)

func file_BannerRotationService_proto_rawDescGZIP() []byte {
	file_BannerRotationService_proto_rawDescOnce.Do(func() {
		file_BannerRotationService_proto_rawDescData = protoimpl.X.CompressGZIP(file_BannerRotationService_proto_rawDescData)
	})
	return file_BannerRotationService_proto_rawDescData
}

var file_BannerRotationService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_BannerRotationService_proto_goTypes = []any{
	(*SelectBannerRequest)(nil),         // 0: SelectBannerRequest
	(*SelectBannerResponse)(nil),        // 1: SelectBannerResponse
	(*ClickBannerRequest)(nil),          // 2: ClickBannerRequest
	(*AddBannerToSlotRequest)(nil),      // 3: AddBannerToSlotRequest
	(*RemoveBannerFromSlotRequest)(nil), // 4: RemoveBannerFromSlotRequest
	(*empty.Empty)(nil),                 // 5: google.protobuf.Empty
}
var file_BannerRotationService_proto_depIdxs = []int32{
	0, // 0: Banners.ShowBanner:input_type -> SelectBannerRequest
	2, // 1: Banners.ClickBanner:input_type -> ClickBannerRequest
	3, // 2: Banners.AddBannerToSlot:input_type -> AddBannerToSlotRequest
	4, // 3: Banners.RemoveBannerFromSlot:input_type -> RemoveBannerFromSlotRequest
	1, // 4: Banners.ShowBanner:output_type -> SelectBannerResponse
	5, // 5: Banners.ClickBanner:output_type -> google.protobuf.Empty
	5, // 6: Banners.AddBannerToSlot:output_type -> google.protobuf.Empty
	5, // 7: Banners.RemoveBannerFromSlot:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BannerRotationService_proto_init() }
func file_BannerRotationService_proto_init() {
	if File_BannerRotationService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BannerRotationService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BannerRotationService_proto_goTypes,
		DependencyIndexes: file_BannerRotationService_proto_depIdxs,
		MessageInfos:      file_BannerRotationService_proto_msgTypes,
	}.Build()
	File_BannerRotationService_proto = out.File
	file_BannerRotationService_proto_rawDesc = nil
	file_BannerRotationService_proto_goTypes = nil
	file_BannerRotationService_proto_depIdxs = nil
}
