// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: BannerRotationService.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Banners_ShowBanner_FullMethodName           = "/Banners/ShowBanner"
	Banners_ClickBanner_FullMethodName          = "/Banners/ClickBanner"
	Banners_AddBannerToSlot_FullMethodName      = "/Banners/AddBannerToSlot"
	Banners_RemoveBannerFromSlot_FullMethodName = "/Banners/RemoveBannerFromSlot"
	Banners_CreateBanner_FullMethodName         = "/Banners/CreateBanner"
	Banners_UpdateBanner_FullMethodName         = "/Banners/UpdateBanner"
	Banners_GetBanner_FullMethodName            = "/Banners/GetBanner"
	Banners_DeleteBanner_FullMethodName         = "/Banners/DeleteBanner"
	Banners_CreateGroup_FullMethodName          = "/Banners/CreateGroup"
	Banners_UpdateGroup_FullMethodName          = "/Banners/UpdateGroup"
	Banners_GetGroup_FullMethodName             = "/Banners/GetGroup"
	Banners_DeleteGroup_FullMethodName          = "/Banners/DeleteGroup"
	Banners_CreateSlot_FullMethodName           = "/Banners/CreateSlot"
	Banners_UpdateSlot_FullMethodName           = "/Banners/UpdateSlot"
	Banners_GetSlot_FullMethodName              = "/Banners/GetSlot"
	Banners_DeleteSlot_FullMethodName           = "/Banners/DeleteSlot"
)

// BannersClient is the client API for Banners service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannersClient interface {
	ShowBanner(ctx context.Context, in *SelectBannerRequest, opts ...grpc.CallOption) (*SelectBannerResponse, error)
	ClickBanner(ctx context.Context, in *ClickBannerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddBannerToSlot(ctx context.Context, in *AddBannerToSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveBannerFromSlot(ctx context.Context, in *RemoveBannerFromSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*SingleBannerResponse, error)
	UpdateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*SingleBannerResponse, error)
	GetBanner(ctx context.Context, in *BannerIdRequest, opts ...grpc.CallOption) (*SingleBannerResponse, error)
	DeleteBanner(ctx context.Context, in *BannerIdRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*SingleGroupResponse, error)
	UpdateGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*SingleGroupResponse, error)
	GetGroup(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*SingleGroupResponse, error)
	DeleteGroup(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (*SingleSlotResponse, error)
	UpdateSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (*SingleSlotResponse, error)
	GetSlot(ctx context.Context, in *SlotIdRequest, opts ...grpc.CallOption) (*SingleSlotResponse, error)
	DeleteSlot(ctx context.Context, in *SlotIdRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type bannersClient struct {
	cc grpc.ClientConnInterface
}

func NewBannersClient(cc grpc.ClientConnInterface) BannersClient {
	return &bannersClient{cc}
}

func (c *bannersClient) ShowBanner(ctx context.Context, in *SelectBannerRequest, opts ...grpc.CallOption) (*SelectBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectBannerResponse)
	err := c.cc.Invoke(ctx, Banners_ShowBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) ClickBanner(ctx context.Context, in *ClickBannerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_ClickBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) AddBannerToSlot(ctx context.Context, in *AddBannerToSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_AddBannerToSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) RemoveBannerFromSlot(ctx context.Context, in *RemoveBannerFromSlotRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_RemoveBannerFromSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) CreateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*SingleBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleBannerResponse)
	err := c.cc.Invoke(ctx, Banners_CreateBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) UpdateBanner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*SingleBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleBannerResponse)
	err := c.cc.Invoke(ctx, Banners_UpdateBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) GetBanner(ctx context.Context, in *BannerIdRequest, opts ...grpc.CallOption) (*SingleBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleBannerResponse)
	err := c.cc.Invoke(ctx, Banners_GetBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) DeleteBanner(ctx context.Context, in *BannerIdRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_DeleteBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) CreateGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*SingleGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleGroupResponse)
	err := c.cc.Invoke(ctx, Banners_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) UpdateGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*SingleGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleGroupResponse)
	err := c.cc.Invoke(ctx, Banners_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) GetGroup(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*SingleGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleGroupResponse)
	err := c.cc.Invoke(ctx, Banners_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) DeleteGroup(ctx context.Context, in *GroupIdRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) CreateSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (*SingleSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleSlotResponse)
	err := c.cc.Invoke(ctx, Banners_CreateSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) UpdateSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (*SingleSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleSlotResponse)
	err := c.cc.Invoke(ctx, Banners_UpdateSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) GetSlot(ctx context.Context, in *SlotIdRequest, opts ...grpc.CallOption) (*SingleSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleSlotResponse)
	err := c.cc.Invoke(ctx, Banners_GetSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannersClient) DeleteSlot(ctx context.Context, in *SlotIdRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Banners_DeleteSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannersServer is the server API for Banners service.
// All implementations must embed UnimplementedBannersServer
// for forward compatibility.
type BannersServer interface {
	ShowBanner(context.Context, *SelectBannerRequest) (*SelectBannerResponse, error)
	ClickBanner(context.Context, *ClickBannerRequest) (*empty.Empty, error)
	AddBannerToSlot(context.Context, *AddBannerToSlotRequest) (*empty.Empty, error)
	RemoveBannerFromSlot(context.Context, *RemoveBannerFromSlotRequest) (*empty.Empty, error)
	CreateBanner(context.Context, *BannerRequest) (*SingleBannerResponse, error)
	UpdateBanner(context.Context, *BannerRequest) (*SingleBannerResponse, error)
	GetBanner(context.Context, *BannerIdRequest) (*SingleBannerResponse, error)
	DeleteBanner(context.Context, *BannerIdRequest) (*empty.Empty, error)
	CreateGroup(context.Context, *GroupRequest) (*SingleGroupResponse, error)
	UpdateGroup(context.Context, *GroupRequest) (*SingleGroupResponse, error)
	GetGroup(context.Context, *GroupIdRequest) (*SingleGroupResponse, error)
	DeleteGroup(context.Context, *GroupIdRequest) (*empty.Empty, error)
	CreateSlot(context.Context, *SlotRequest) (*SingleSlotResponse, error)
	UpdateSlot(context.Context, *SlotRequest) (*SingleSlotResponse, error)
	GetSlot(context.Context, *SlotIdRequest) (*SingleSlotResponse, error)
	DeleteSlot(context.Context, *SlotIdRequest) (*empty.Empty, error)
	mustEmbedUnimplementedBannersServer()
}

// UnimplementedBannersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBannersServer struct{}

func (UnimplementedBannersServer) ShowBanner(context.Context, *SelectBannerRequest) (*SelectBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowBanner not implemented")
}
func (UnimplementedBannersServer) ClickBanner(context.Context, *ClickBannerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickBanner not implemented")
}
func (UnimplementedBannersServer) AddBannerToSlot(context.Context, *AddBannerToSlotRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBannerToSlot not implemented")
}
func (UnimplementedBannersServer) RemoveBannerFromSlot(context.Context, *RemoveBannerFromSlotRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBannerFromSlot not implemented")
}
func (UnimplementedBannersServer) CreateBanner(context.Context, *BannerRequest) (*SingleBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBanner not implemented")
}
func (UnimplementedBannersServer) UpdateBanner(context.Context, *BannerRequest) (*SingleBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBanner not implemented")
}
func (UnimplementedBannersServer) GetBanner(context.Context, *BannerIdRequest) (*SingleBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBanner not implemented")
}
func (UnimplementedBannersServer) DeleteBanner(context.Context, *BannerIdRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedBannersServer) CreateGroup(context.Context, *GroupRequest) (*SingleGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedBannersServer) UpdateGroup(context.Context, *GroupRequest) (*SingleGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedBannersServer) GetGroup(context.Context, *GroupIdRequest) (*SingleGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedBannersServer) DeleteGroup(context.Context, *GroupIdRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedBannersServer) CreateSlot(context.Context, *SlotRequest) (*SingleSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlot not implemented")
}
func (UnimplementedBannersServer) UpdateSlot(context.Context, *SlotRequest) (*SingleSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlot not implemented")
}
func (UnimplementedBannersServer) GetSlot(context.Context, *SlotIdRequest) (*SingleSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlot not implemented")
}
func (UnimplementedBannersServer) DeleteSlot(context.Context, *SlotIdRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSlot not implemented")
}
func (UnimplementedBannersServer) mustEmbedUnimplementedBannersServer() {}
func (UnimplementedBannersServer) testEmbeddedByValue()                 {}

// UnsafeBannersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannersServer will
// result in compilation errors.
type UnsafeBannersServer interface {
	mustEmbedUnimplementedBannersServer()
}

func RegisterBannersServer(s grpc.ServiceRegistrar, srv BannersServer) {
	// If the following call pancis, it indicates UnimplementedBannersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Banners_ServiceDesc, srv)
}

func _Banners_ShowBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).ShowBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_ShowBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).ShowBanner(ctx, req.(*SelectBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_ClickBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).ClickBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_ClickBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).ClickBanner(ctx, req.(*ClickBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_AddBannerToSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBannerToSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).AddBannerToSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_AddBannerToSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).AddBannerToSlot(ctx, req.(*AddBannerToSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_RemoveBannerFromSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBannerFromSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).RemoveBannerFromSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_RemoveBannerFromSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).RemoveBannerFromSlot(ctx, req.(*RemoveBannerFromSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_CreateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).CreateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_CreateBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).CreateBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_UpdateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).UpdateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_UpdateBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).UpdateBanner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_GetBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).GetBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_GetBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).GetBanner(ctx, req.(*BannerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_DeleteBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).DeleteBanner(ctx, req.(*BannerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).CreateGroup(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).UpdateGroup(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).GetGroup(ctx, req.(*GroupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).DeleteGroup(ctx, req.(*GroupIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_CreateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).CreateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_CreateSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).CreateSlot(ctx, req.(*SlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_UpdateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).UpdateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_UpdateSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).UpdateSlot(ctx, req.(*SlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_GetSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).GetSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_GetSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).GetSlot(ctx, req.(*SlotIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banners_DeleteSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannersServer).DeleteSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banners_DeleteSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannersServer).DeleteSlot(ctx, req.(*SlotIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Banners_ServiceDesc is the grpc.ServiceDesc for Banners service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Banners_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Banners",
	HandlerType: (*BannersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowBanner",
			Handler:    _Banners_ShowBanner_Handler,
		},
		{
			MethodName: "ClickBanner",
			Handler:    _Banners_ClickBanner_Handler,
		},
		{
			MethodName: "AddBannerToSlot",
			Handler:    _Banners_AddBannerToSlot_Handler,
		},
		{
			MethodName: "RemoveBannerFromSlot",
			Handler:    _Banners_RemoveBannerFromSlot_Handler,
		},
		{
			MethodName: "CreateBanner",
			Handler:    _Banners_CreateBanner_Handler,
		},
		{
			MethodName: "UpdateBanner",
			Handler:    _Banners_UpdateBanner_Handler,
		},
		{
			MethodName: "GetBanner",
			Handler:    _Banners_GetBanner_Handler,
		},
		{
			MethodName: "DeleteBanner",
			Handler:    _Banners_DeleteBanner_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Banners_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Banners_UpdateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _Banners_GetGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _Banners_DeleteGroup_Handler,
		},
		{
			MethodName: "CreateSlot",
			Handler:    _Banners_CreateSlot_Handler,
		},
		{
			MethodName: "UpdateSlot",
			Handler:    _Banners_UpdateSlot_Handler,
		},
		{
			MethodName: "GetSlot",
			Handler:    _Banners_GetSlot_Handler,
		},
		{
			MethodName: "DeleteSlot",
			Handler:    _Banners_DeleteSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BannerRotationService.proto",
}
